box: wodby/alpine:3.7-1.1.1

build:
  box:
    id: python:alpine
    cmd: /bin/sh
  steps:
    - script:
      name: build
      code: |
        pip install mkdocs
        pip install markdown-include
        apk add --update bash
        cd docs
        ./build.sh

release:
  box:
    id: wodby/nginx:1.13-3.0.2
    cmd: /bin/sh
    user: root
  steps:
    - script:
      name: mv static files
      code: |
        mv $WERCKER_SOURCE_DIR/build/* /var/www/html
        ls -la /var/www/html
        id
        exit 1
    - internal/docker-push:
      registry: https://registry.hub.docker.com/v2
      username: $DOCKER_USERNAME
      password: $DOCKER_PASSWORD
      repository: wodby/php-docs
      tag: latest, $WERCKER_GIT_BRANCH

deploy:
  steps:
    - script:
      name: deployment
      code: |
        curl -sS \
                -H "Content-type: application/json" \
                -H "Authorization: token ${WODBY_API_TOKEN}" \
                -X POST https://api.wodby.com/api/v2/bundles/deploy?org_id="${WODBY_ORG_UUID}"\&service_image=wodby/docs:"${WERCKER_GIT_BRANCH}"\&cause="${WERCKER_GIT_COMMIT}"
  after-steps:
    - slack-notifier:
      url: $SLACK_URL
      channel: activity
      username: wecker
      branch: master