box: wodby/alpine:3.7-1.1.1

build:
  box:
    id: python:alpine
    cmd: /bin/sh
  steps:
    - script:
      name: build
      code: |
        pip install mkdocs
        pip install markdown-include
        apk add --update bash
        cd docs
        ./build.sh

release:
  steps:
    - script:
      name: install dependencies
      code: |
        apk add --update curl bash
    - script:
      name: mv static files
      code: |
        ls -la
        rm -rf /usr/share/nginx/html/*
        mv $WERCKER_SOURCE_DIR/build/* /usr/share/nginx/html
    - internal/docker-push:
      registry: https://registry.hub.docker.com/v2
      username: $DOCKER_USERNAME
      password: $DOCKER_PASSWORD
      repository: wodby/docs
      tag: latest, $WERCKER_GIT_BRANCH
      cmd: nginx -g 'daemon off;'

deploy:
  steps:
    - script:
      name: deployment
      code: |
        curl -sS \
                -H "Content-type: application/json" \
                -H "Authorization: token ${WODBY_API_TOKEN}" \
                -X POST https://api.wodby.com/api/v2/bundles/deploy?org_id="${WODBY_ORG_UUID}"\&service_image=wodby/docs:"${WERCKER_GIT_BRANCH}"\&cause="${WERCKER_GIT_COMMIT}"
  after-steps:
    - slack-notifier:
      url: $SLACK_URL
      channel: activity
      username: wecker
      branch: master